In [2]:
pip install -U sentence-transformers

   ---------------------------------------- 0.0/588.9 kB ? eta -:--:--
   ---------------------------------------- 0.0/588.9 kB ? eta -:--:--
   ---------------------------------------- 588.9/588.9 kB 1.9 MB/s  0:00:00
  Attempting uninstall: sentence-transformers
    Found existing installation: sentence-transformers 5.4.1
    Uninstalling sentence-transformers-5.4.1:
      Successfully uninstalled sentence-transformers-5.4.1
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
from sentence_transformers import SentenceTransformer,util

In [5]:
model = SentenceTransformer('all-MiniLM-L6-v2')

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

D:\resume-screener\venv\Lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\ROHIT RAJ\.cache\huggingface\hub\models--sentence-transformers--all-MiniLM-L6-v2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)


config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [6]:
sentences = ['This framework generates embeddings for each input sentence',
    'Sentences are passed as a list of string.']


In [7]:
embeddings=model.encode(sentences)

In [8]:
for sentence,embedding in zip(sentences,embeddings):
    print("Sentence: ",sentence)
    print("Embedding: ",embedding)
    

Sentence:  This framework generates embeddings for each input sentence
Embedding:  [-1.37173571e-02 -4.28515188e-02 -1.56285986e-02  1.40537536e-02
  3.95537987e-02  1.21796280e-01  2.94333901e-02 -3.17524076e-02
  3.54959518e-02 -7.93140009e-02  1.75878704e-02 -4.04370092e-02
  4.97259349e-02  2.54911985e-02 -7.18700439e-02  8.14968944e-02
  1.47070142e-03  4.79627326e-02 -4.50336300e-02 -9.92174968e-02
 -2.81769596e-02  6.45046234e-02  4.44670431e-02 -4.76217158e-02
 -3.52952369e-02  4.38671932e-02 -5.28565869e-02  4.33048233e-04
  1.01921506e-01  1.64072346e-02  3.26996446e-02 -3.45986858e-02
  1.21339262e-02  7.94871151e-02  4.58344631e-03  1.57778058e-02
 -9.68204346e-03  2.87626013e-02 -5.05806357e-02 -1.55793801e-02
 -2.87906677e-02 -9.62280948e-03  3.15557010e-02  2.27349047e-02
  8.71449411e-02 -3.85027379e-02 -8.84718671e-02 -8.75499099e-03
 -2.12343168e-02  2.08923258e-02 -9.02077630e-02 -5.25732376e-02
 -1.05638662e-02  2.88310777e-02 -1.61455255e-02  6.17841119e-03
 -1.232

# Cosine - Similarity

In [14]:
# emb1=model.encode(sentences[0])
# emb2=model.encode(sentences[1])

emb1=model.encode('I love Rohit')
emb2=model.encode('Rohit is my love')
similarity=util.cos_sim(emb1,emb2)
print("Similarty: ",similarity*100)

Similarty:  tensor([[91.7196]])


In [17]:
emb1=model.encode('I will clear JEE and get into an IIT')
emb2=model.encode('If your want to go to IIT you need to clear JEE')

similarity=util.cos_sim(emb1,emb2)
similarity*100

tensor([[88.4657]])

In [20]:
emb1=model.encode('for(int i=0;i<10;i++) cout<<i<<endl;')
emb2=model.encode('for(int i=0;i<10;i++) System.out.println(i); ')

similarity=util.cos_sim(emb1,emb2)
similarity*100

tensor([[75.8862]])

# Compute cosine similarity between all pairs

In [21]:
# calculatin cosine similarity across all pairs.

In [27]:
sentences = ['A man is eating food.',
          'A man is eating a piece of bread.',
          'The girl is carrying a baby.',
          'A man is riding a horse.',
          'A woman is playing violin.',
          'Two men pushed carts through the woods.',
          'A man is riding a white horse on an enclosed ground.',
          'A monkey is playing drums.',
          'Someone in a gorilla costume is playing a set of drums.'
          ]

embedding = model.encode(sentences)
sim = util.cos_sim(embedding,embedding)
sim

tensor([[ 1.0000,  0.7553, -0.1050,  0.2474, -0.0704, -0.0333,  0.1707,  0.0476,
          0.0630],
        [ 0.7553,  1.0000, -0.0610,  0.1442, -0.0809, -0.0216,  0.1157,  0.0362,
          0.0216],
        [-0.1050, -0.0610,  1.0000, -0.1088,  0.0217, -0.0413, -0.0928,  0.0231,
          0.0247],
        [ 0.2474,  0.1442, -0.1088,  1.0000, -0.0348,  0.0362,  0.7369,  0.0821,
          0.1389],
        [-0.0704, -0.0809,  0.0217, -0.0348,  1.0000, -0.1654, -0.0592,  0.1961,
          0.2564],
        [-0.0333, -0.0216, -0.0413,  0.0362, -0.1654,  1.0000,  0.0769, -0.0380,
         -0.0895],
        [ 0.1707,  0.1157, -0.0928,  0.7369, -0.0592,  0.0769,  1.0000,  0.0495,
          0.1191],
        [ 0.0476,  0.0362,  0.0231,  0.0821,  0.1961, -0.0380,  0.0495,  1.0000,
          0.6433],
        [ 0.0630,  0.0216,  0.0247,  0.1389,  0.2564, -0.0895,  0.1191,  0.6433,
          1.0000]])

In [28]:
# Task 1 Sort these and then find sentences which have highest cosine similarties.

In [29]:
#  first we need to remove duplicate pairs ->  (0,2) & (2,0)

In [33]:
pairs=[]

for i in range(len(sentences)):
    for j in range(i+1,len(sentences)):
        pairs.append((sim[i][j],i,j))
pairs   

[(tensor(0.7553), 0, 1),
 (tensor(-0.1050), 0, 2),
 (tensor(0.2474), 0, 3),
 (tensor(-0.0704), 0, 4),
 (tensor(-0.0333), 0, 5),
 (tensor(0.1707), 0, 6),
 (tensor(0.0476), 0, 7),
 (tensor(0.0630), 0, 8),
 (tensor(-0.0610), 1, 2),
 (tensor(0.1442), 1, 3),
 (tensor(-0.0809), 1, 4),
 (tensor(-0.0216), 1, 5),
 (tensor(0.1157), 1, 6),
 (tensor(0.0362), 1, 7),
 (tensor(0.0216), 1, 8),
 (tensor(-0.1088), 2, 3),
 (tensor(0.0217), 2, 4),
 (tensor(-0.0413), 2, 5),
 (tensor(-0.0928), 2, 6),
 (tensor(0.0231), 2, 7),
 (tensor(0.0247), 2, 8),
 (tensor(-0.0348), 3, 4),
 (tensor(0.0362), 3, 5),
 (tensor(0.7369), 3, 6),
 (tensor(0.0821), 3, 7),
 (tensor(0.1389), 3, 8),
 (tensor(-0.1654), 4, 5),
 (tensor(-0.0592), 4, 6),
 (tensor(0.1961), 4, 7),
 (tensor(0.2564), 4, 8),
 (tensor(0.0769), 5, 6),
 (tensor(-0.0380), 5, 7),
 (tensor(-0.0895), 5, 8),
 (tensor(0.0495), 6, 7),
 (tensor(0.1191), 6, 8),
 (tensor(0.6433), 7, 8)]

In [35]:
pairs.sort(reverse=True)

In [36]:
pairs

[(tensor(0.7553), 0, 1),
 (tensor(0.7369), 3, 6),
 (tensor(0.6433), 7, 8),
 (tensor(0.2564), 4, 8),
 (tensor(0.2474), 0, 3),
 (tensor(0.1961), 4, 7),
 (tensor(0.1707), 0, 6),
 (tensor(0.1442), 1, 3),
 (tensor(0.1389), 3, 8),
 (tensor(0.1191), 6, 8),
 (tensor(0.1157), 1, 6),
 (tensor(0.0821), 3, 7),
 (tensor(0.0769), 5, 6),
 (tensor(0.0630), 0, 8),
 (tensor(0.0495), 6, 7),
 (tensor(0.0476), 0, 7),
 (tensor(0.0362), 1, 7),
 (tensor(0.0362), 3, 5),
 (tensor(0.0247), 2, 8),
 (tensor(0.0231), 2, 7),
 (tensor(0.0217), 2, 4),
 (tensor(0.0216), 1, 8),
 (tensor(-0.0216), 1, 5),
 (tensor(-0.0333), 0, 5),
 (tensor(-0.0348), 3, 4),
 (tensor(-0.0380), 5, 7),
 (tensor(-0.0413), 2, 5),
 (tensor(-0.0592), 4, 6),
 (tensor(-0.0610), 1, 2),
 (tensor(-0.0704), 0, 4),
 (tensor(-0.0809), 1, 4),
 (tensor(-0.0895), 5, 8),
 (tensor(-0.0928), 2, 6),
 (tensor(-0.1050), 0, 2),
 (tensor(-0.1088), 2, 3),
 (tensor(-0.1654), 4, 5)]

In [37]:
for score,i,j in pairs:
    print(sentences[i],sentences[j],score)

A man is eating food. A man is eating a piece of bread. tensor(0.7553)
A man is riding a horse. A man is riding a white horse on an enclosed ground. tensor(0.7369)
A monkey is playing drums. Someone in a gorilla costume is playing a set of drums. tensor(0.6433)
A woman is playing violin. Someone in a gorilla costume is playing a set of drums. tensor(0.2564)
A man is eating food. A man is riding a horse. tensor(0.2474)
A woman is playing violin. A monkey is playing drums. tensor(0.1961)
A man is eating food. A man is riding a white horse on an enclosed ground. tensor(0.1707)
A man is eating a piece of bread. A man is riding a horse. tensor(0.1442)
A man is riding a horse. Someone in a gorilla costume is playing a set of drums. tensor(0.1389)
A man is riding a white horse on an enclosed ground. Someone in a gorilla costume is playing a set of drums. tensor(0.1191)
A man is eating a piece of bread. A man is riding a white horse on an enclosed ground. tensor(0.1157)
A man is riding a horse

# Testing

In [40]:
job_description=[
'''
Job Title: Senior Full-Stack Web Developer
About the Role
We are looking for a skilled and passionate Senior Full-Stack Web Developer with 5 years of professional experience to join our growing engineering team. In this role, you will own features from conception to deployment, bridging the gap between elegant user interfaces and robust, scalable backend architecture.

As a mid-to-senior level engineer, you won't just write code—you will help architect systems, mentor junior developers, and collaborate closely with product managers and designers to build impactful digital products.

Core Responsibilities
End-to-End Development: Design, build, and maintain efficient, reusable, and reliable front-end and back-end code.

System Architecture: Assist in designing scalable database schemas, API structures, and system integrations.

UI/UX Collaboration: Translate wireframes and Figma designs into high-quality, responsive web interfaces with a focus on user experience.

Performance Optimization: Identify bottlenecks and bugs, and devise solutions to mitigate and solve these issues for maximum speed and scalability.

Code Quality & DevOps: Participate in and lead code reviews, maintain high test coverage, and support automated CI/CD deployment pipelines.

Mentorship: Guide and support junior and mid-level developers, fostering a culture of continuous learning and technical excellence.

Required Skills & Qualifications
Experience
Minimum 5 years of professional experience in full-stack web application development.

Proven track record of shipping production-grade web applications from scratch.

Frontend Tech Stack
Deep expertise in HTML5, CSS3, and modern JavaScript (ES6+) or TypeScript.

Strong experience with modern frontend frameworks, specifically React.js, Vue.js, or Angular (we primarily use [Insert your primary framework, e.g., React]).

Experience with state management libraries (e.g., Redux, Zustand) and modern styling tools (e.g., Tailwind CSS, SASS).

Backend Tech Stack
Solid experience with server-side languages/environments, preferably Node.js (Express/NestJS), Python (Django/FastAPI), or Ruby on Rails (we primarily use [Insert your primary backend]).

Strong understanding of RESTful API design and implementation (GraphQL experience is a plus).

Data & Infrastructure
Proficiency with relational databases (PostgreSQL, MySQL) and/or NoSQL databases (MongoDB).

Experience with version control systems (Git/GitHub) and Gitflow workflow.

Familiarity with cloud platforms (AWS, GCP, or Azure) and containerization (Docker).

Preferred/Bonus Qualifications
Experience with Next.js or Nuxt.js for SSR (Server-Side Rendering).

Knowledge of modern CI/CD tools (GitHub Actions, Jenkins, CircleCI).

Understanding of web security best practices (OWASP Top 10).

Experience working in an Agile/Scrum development environment.

What We Offer
Competitive salary and performance-based bonuses.

Comprehensive health, dental, and vision insurance.

Flexible remote work options and flexible PTO.

Annual learning and development stipend for courses, conferences, or certifications.

State-of-the-art hardware and home office setup allowance.
'''
]

resume=['''
Alex Morgan
SENIOR FULL-STACK WEB DEVELOPER

alex.morgan.dev@email.com • +1 (555) 234-5678
San Francisco, CA • linkedin.com/in/alexmorgan
github.com/alexmorgan-dev • alexmorgan.dev

PROFESSIONAL SUMMARY
Dynamic and solutions-driven Full-Stack Web Developer with 5 years of
professional experience designing, building, and deploying robust, scalable,
production-grade web applications. Expert in modern frontend ecosystems

centered around React and TypeScript, seamlessly paired with high-
performance Node.js backend architectures. Proven record of optimization,

translating complex designs into responsive UIs, and leading technical
feature architecture. Commited to writing clean, testable code and
leveraging CI/CD pipelines to ensure continuous delivery and operational
excellence.
PROFESSIONAL EXPERIENCE
Senior Full-Stack Engineer / InnovateTech
Solutions

2023 – Present •
Remote
Architected and implemented a high-traffic SaaS dashboard using React,
TypeScript, and NestJS, improving initial page load time by 35% via
code-splitting and server-side optimization.
Designed scalable PostgreSQL relational schemas and optimized
complex queries, reducing API latency metrics by 42%.
Collaborated intimately with product managers and designers to translate
Figma design tokens into an accessible, highly interactive UI layout using
Tailwind CSS.
Mentored 3 junior and mid-level engineers, enforcing industry best
practices via rigorous code reviews and weekly pair-programming
sprints.
Integrated Docker into local workflows and automated production release
deployment pipelines using GitHub Actions, cutting release cycles from
weekly to on-demand.

TECHNICAL SKILLS
FRONTEND STACK
React.js TypeScript
JavaScript (ES6+) Next.js
HTML5 & CSS3 Tailwind CSS
Redux Toolkit Zustand
BACKEND & DATA
Node.js Express.js NestJS
PostgreSQL MySQL
MongoDB RESTful APIs
GraphQL
DEVOPS & TOOLS
Git / GitHub Docker
AWS (S3, EC2) GitHub Actions
CI/CD Pipelines Jest
Figma Integration
KEY PROJECTS
CollabTask - Management Tool
Next.js, Node.js, Socket.io, PostgreSQL
Designed a real-time collaborative
workspace utilizing WebSockets to
handle concurrently mutating UI states
for thousands of active sessions.
ShopSwift E-Commerce Platform
React, Node.js, Stripe, MongoDB
Engineered an end-to-end scalable
checkout workflow featuring strict
transaction state isolation and custom
webhooks handlers.
EDUCATION
B.S. in Computer Science
University of California, Berkeley
Graduated 2021

•

•

•

•

•

Page 1 of 2

Full-Stack Web Developer / PixelCraft Digital
Agency

2021 – 2023 • San
Francisco, CA
Developed and launched 8+ tailored E-commerce and enterprise web
applications utilizing the MERN stack (MongoDB, Express, React,
Node.js).
Built secure, robust, and fully documented RESTful APIs adhering to
clean architecture standards and implemented JWT-based authentication
mechanisms.
Championed web application security audits using OWASP Top 10
guidelines, eliminating critical cross-site scripting (XSS) vulnerabilities.
Configured state management solutions using Redux Toolkit to
seamlessly synchronize deep client-side data state with remote database
persistence layers.
Maintained 90%+ testing coverage across core server utilities using Jest
and Supertest, ensuring system stability.
''']

emb1=model.encode(job_description)
emb2=model.encode(resume)

sim=util.cos_sim(emb1,emb2)

sim*100


tensor([[72.5488]])

# Semantic Search

In [6]:
from sentence_transformers import SentenceTransformer,util

In [7]:
model=SentenceTransformer('clips/mfaq')

D:\resume-screener\venv\Lib\site-packages\transformers\configuration_utils.py:312: UserWarning: Passing `gradient_checkpointing` to a config initialization is deprecated and will be removed in v5 Transformers. Using `model.gradient_checkpointing_enable()` instead, or if you are using the `Trainer` API, pass `gradient_checkpointing=True` in your `TrainingArguments`.
  warnings.warn(


In [43]:
question = "How many models can I host on HuggingFace?"
answer_1 = "HuggingFace allows max 5 model hosting per user."
answer_2 = "AutoNLP is an automatic way to train and deploy state-of-the-art NLP models, seamlessly integrated with the Hugging Face ecosystem."
answer_3 = "Based on how much training data and model variants are created, we send you a compute cost and payment link - as low as $10 per job."

In [45]:
query_embedding = model.encode(question)

In [49]:
answer_embedding = model.encode([answer_1,answer_2,answer_3])

In [50]:
print(util.semantic_search(query_embedding,answer_embedding))

[[{'corpus_id': 0, 'score': 0.6061518788337708}, {'corpus_id': 2, 'score': 0.49931800365448}, {'corpus_id': 1, 'score': 0.45967167615890503}]]


In [1]:
!pip install transformers


[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import transformers

In [7]:
print(transformers.__version__)

4.52.4


In [8]:
from transformers import pipeline

In [13]:
qa_model=pipeline('question-answering',model="deepset/roberta-base-squad2")

config.json:   0%|          | 0.00/571 [00:00<?, ?B/s]

D:\resume-screener\venv\Lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\ROHIT RAJ\.cache\huggingface\hub\models--deepset--roberta-base-squad2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)


model.safetensors:   0%|          | 0.00/496M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/79.0 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/772 [00:00<?, ?B/s]

Device set to use cpu


In [1]:
question='What is my homeState'
context='I am Rohit Raj, I am from Sonpur,that is in Bihar(homeState)'
qa_model(question=question,context=context)

NameError: name 'qa_model' is not defined

# Clustering

In [1]:
from sklearn.cluster import KMeans
import numpy as np

In [2]:
# Corpus with example sentences
corpus = ['A man is eating food.',
          'A man is eating a piece of bread.',
          'Horse is eating grass.',
          'A man is eating pasta.',
          'A Woman is eating Biryani.',
          'The girl is carrying a baby.',
          'The baby is carried by the woman',
          'A man is riding a horse.',
          'A man is riding a white horse on an enclosed ground.',
          'A monkey is playing drums.',
          'Someone in a gorilla costume is playing a set of drums.',
          'A cheetah is running behind its prey.',
          'A cheetah chases prey on across a field.',
          'The cheetah is chasing a man who is riding the horse.',
          'man and women with their baby are watching cheetah in zoo'
          ]

In [8]:
corpus_embeddings = model.encode(corpus)

In [9]:
corpus_embeddings = corpus_embeddings /  np.linalg.norm(corpus_embeddings, axis=1, keepdims=True)

In [12]:
# source: https://stackoverflow.com/questions/55619176/how-to-cluster-similar-sentences-using-bert

clustering_model = KMeans(n_clusters=6)
clustering_model.fit(corpus_embeddings)
cluster_assignment = clustering_model.labels_
print(cluster_assignment)

[3 3 3 3 3 2 2 4 4 4 0 5 5 1 1]


In [13]:
clustered_sentences = {}
for sentence_id, cluster_id in enumerate(cluster_assignment):
    if cluster_id not in clustered_sentences:
        clustered_sentences[cluster_id] = []

    clustered_sentences[cluster_id].append(corpus[sentence_id])
clustered_sentences

{np.int32(3): ['A man is eating food.',
  'A man is eating a piece of bread.',
  'Horse is eating grass.',
  'A man is eating pasta.',
  'A Woman is eating Biryani.'],
 np.int32(2): ['The girl is carrying a baby.',
  'The baby is carried by the woman'],
 np.int32(4): ['A man is riding a horse.',
  'A man is riding a white horse on an enclosed ground.',
  'A monkey is playing drums.'],
 np.int32(0): ['Someone in a gorilla costume is playing a set of drums.'],
 np.int32(5): ['A cheetah is running behind its prey.',
  'A cheetah chases prey on across a field.'],
 np.int32(1): ['The cheetah is chasing a man who is riding the horse.',
  'man and women with their baby are watching cheetah in zoo']}